name: PermissionManager
version: '${version}'
description: demo Project
main: com.tinyshellzz.permissionManager.PermissionManager
api-version: '1.20'
load: POSTWORLD
softdepend: [ PlaceholderAPI ]
authors: [ Tinyshellzz ]
folia-supported: true
website: https://github.com/
commands:
  perm:
    description: permission management
    usage: /perm <give|remove> <player> <permissionNode>
    permission: perm.use
permissions:
  perm.use:
    default: false
    description: Allows using /perm give and /perm remove
